FROM golang:alpine as builder

LABEL maintainer="DiscordBot"

RUN apk update && apk add --no-cache git

WORKDIR /app

COPY ../go.mod go.sum ./

RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o ./build/discordBot cmd/main.go

FROM alpine:latest

RUN apk --no-cache add ca-certificates

WORKDIR /app

COPY --from=builder /app/build/discordBot .
COPY --from=builder /app/configs configs

EXPOSE 8080

CMD ["/app/discordBot"]